---
title: "E14 scRNA analysis with process and parameters standardized with rV2 project"
output: html_notebook
---

```{r Loading libraries, include=FALSE}
library(Seurat);
library(tidyverse);
library(ggplot2);
library(future);
library(org.Mm.eg.db);
library(DT);
library(data.table);
library(qs)
library(readxl)
library(ggsci)
library(grid)
library(randomcoloR)
source("AdditionalFunctions.R");
```

```{r Setting Seurat multicore}
plan("multisession", workers = 6)
options(future.globals.maxSize = 12 * 1024 ^ 3, future.rng.onMisuse="ignore")
```

```{r Setting variable}
sample.name <- "E14"
run.date <- "070923"
```

```{r Reading datafiles and form Seurat objects - DI}
  di.repl1 <- Read10X(data.dir = "/Volumes/MyBookDuo/Data/e14di_data/scRNA/E14_DI_1_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  di.s.repl1 <- CreateSeuratObject(counts = di.repl1, project = "DI")

  di.repl2 <- Read10X(data.dir = "/Volumes/MyBookDuo/Data/e14di_data/scRNA/E14_DI_2_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  di.s.repl2 <- CreateSeuratObject(counts = di.repl2, project = "DI")
```

```{r Read Ensembl to gene name mapping from 10x datafiles for both Seurat objects - DI}
di.feature.data.repl1 <- as.data.frame(setNames(fread("/Volumes/MyBookDuo/Data/e14di_data/scRNA/E14_DI_1_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))

di.feature.data.repl2 <- as.data.frame(setNames(fread("/Volumes/MyBookDuo/Data/e14di_data/scRNA/E14_DI_2_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))
```

```{r Reading datafiles and form Seurat objects - R1}
  r1.repl1 <- Read10X(data.dir = "/Volumes/MyBookDuo/Data/e14vr1_data/scRNA/E14vR1_1_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  r1.s.repl1 <- CreateSeuratObject(counts = r1.repl1, project = "R1")

  r1.repl2 <- Read10X(data.dir = "/Volumes/MyBookDuo/Data/e14vr1_data/scRNA/E14vR1_2_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  r1.s.repl2 <- CreateSeuratObject(counts = r1.repl2, project = "R1")
```

```{r Read Ensembl to gene name mapping from 10x datafiles for both Seurat objects - R1}
r1.feature.data.repl1 <- as.data.frame(setNames(fread("/Volumes/MyBookDuo/Data/e14vr1_data/scRNA/E14vR1_1_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))

r1.feature.data.repl2 <- as.data.frame(setNames(fread("/Volumes/MyBookDuo/Data/e14vr1_data/scRNA/E14vR1_2_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))
```

```{r Reading datafiles and form Seurat objects - MB}
  mb.repl1 <- Read10X(data.dir = "/Volumes/MyBookDuo/Data/e14vmb1_data/scRNA/E14VMB_1_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  mb.s.repl1 <- CreateSeuratObject(counts = mb.repl1, project = "MB")

  mb.repl2 <- Read10X(data.dir = "/Volumes/MyBookDuo/Data/e14vmb1_data/scRNA/E14VMB_2_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  mb.s.repl2 <- CreateSeuratObject(counts = mb.repl2, project = "MB")
```

```{r Read Ensembl to gene name mapping from 10x datafiles for both Seurat objects - MB}
mb.feature.data.repl1 <- as.data.frame(setNames(fread("/Volumes/MyBookDuo/Data/e14vmb1_data/scRNA/E14VMB_1_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))

mb.feature.data.repl2 <- as.data.frame(setNames(fread("/Volumes/MyBookDuo/Data/e14vmb1_data/scRNA/E14VMB_2_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))
```

```{r Merging Seurat objects}
s.data_RNA<- merge(x = di.s.repl1, y = list(di.s.repl2,r1.s.repl1, r1.s.repl2, mb.s.repl1, mb.s.repl2), add.cell.ids = c( "di.repl1", "di.repl2", "r1.repl1", "r1.repl2", "mb.repl1", "mb.repl2"), project = "e14.rna.data")
```

```{r Adding feature metadata after merge}
# Note, assumes identical feature metadata between replicates
gene.ii <- match(rownames(s.data_RNA), di.feature.data.repl1[,1])
gene.symbols <- di.feature.data.repl1[gene.ii,2]

s.data_RNA[['RNA']] <- AddMetaData(object = s.data_RNA[['RNA']], metadata = gene.symbols, col.name="feature_symbol")
```

```{r Remove TDTOMATOG}
s.data_RNA <- subset(s.data_RNA, features=rownames(s.data_RNA)[!rownames(s.data_RNA)=="TDTOMATOG"])
```

```{r Calculate percentage of mt- features}
feature.map <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = rownames(s.data_RNA), feature.format = "ens")

mt.features <- rownames(s.data_RNA[grep("^MT-", feature.map, ignore.case = T)])

s.data_RNA[["percent.mt"]] <- PercentageFeatureSet(s.data_RNA, features = mt.features)
```

```{r Plot nFeature_RNA and mitochondrial genes per cell before filtering, fig.height=6, fig.width=10}
VlnPlot(s.data_RNA, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r Filtering likely cell doublets and noise}
s.data_RNA <- subset(s.data_RNA, subset = nFeature_RNA > 2500 & nFeature_RNA < 6000 & percent.mt < 15)
```

```{r Plot nFeature_RNA and mitochondrial genes per cell after filtering,fig.height=6, fig.width=10}
VlnPlot(s.data_RNA, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r LogNormalize data}
s.data_RNA <- NormalizeData(s.data_RNA, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r Finding variable features}
s.data_RNA <- FindVariableFeatures(s.data_RNA, selection.method = "vst", nfeatures = 3000)
```

```{r Scaling data while regressing percent.mt}
s.data_RNA <- ScaleData(s.data_RNA, vars.to.regress = c("percent.mt","nFeature_RNA","nCount_RNA"))
```

```{r Identify 10 most highly variable genes}
top10 <- head(VariableFeatures(s.data_RNA), 10)
```

```{r Plot variable features with and without labels}
plot1 <- VariableFeaturePlot(s.data_RNA)
plot1
LabelPoints(plot = plot1, points = top10, repel = TRUE, labels=convert_feature_identity(object = s.data_RNA, assay = "RNA", features = top10, feature.format = "ens"))
```


```{r RunPCA, include=FALSE}
s.data_RNA <- RunPCA(s.data_RNA, features = VariableFeatures(object = s.data_RNA))
```

```{r Draw Elbowplot}
ElbowPlot(s.data_RNA, ndims=50)
```

```{r Calculate how many dimensions to take}
std.aim <- 0.15
std.proportion <- sapply(1:length(s.data_RNA@reductions$pca@stdev),function(x){s.data_RNA@reductions$pca@stdev[x]/s.data_RNA@reductions$pca@stdev[1]})

# Finding number of components of which std proportion to 2nd component is closest to std.aim
max.pca.dim <- which.min(abs(std.proportion-std.aim))
```

```{r RunUMAP}
s.data_RNA <- RunUMAP(s.data_RNA, dims = 1:max.pca.dim, spread=1)
```

```{r Save data for chooseR interation}
qsave(s.data_RNA, file=paste("../scRNA_data/E14_scRNA_for_chooseR.",run.date,".qs",sep=""), nthreads = 6)
# Using script choose_R_server_side.R 
# Summarize results with chooseR_results.R
# Continue with selected r value
s.data_RNA <- qread(file="../scRNA_data/E14_scRNA_for_chooseR.010823.qs", nthreads = 6)
```


```{r Find neighbours and clusters, message=FALSE}
reduction <- "pca"
assay <- "RNA"
resolution <- 5
algorithm <- 1
s.data_RNA <- Seurat::FindNeighbors(
    s.data_RNA,
    dims = 1:max.pca.dim,
    graph.name = c(paste("N",reduction, assay, sep = "."))
)

s.data_RNA <- Seurat::FindClusters(
    s.data_RNA,
	algorithm = algorithm,
    resolution = resolution,
	method="igraph",
    graph.name = paste("N",reduction, assay, sep = "."),
    verbose = FALSE
  )

```

```{r Draw DimPlot, fig.height=10, fig.width=10}
palette <- ggsci::pal_npg()(length(levels(Idents(s.data_RNA))))
DimPlot(s.data_RNA, reduction = "umap", label = TRUE) + coord_fixed() + theme(legend.pos="none")
```

```{r Some validation plots, fig.height=24, fig.width=18}
markers.symbols <-  c("Gad1", "Slc17a6", "Dlx1", "Tal2", "Pou4f1", "Dlx2","Ascl1","Nkx2-2", "Sst")
markers.id <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = markers.symbols, feature.format = "symbol")

f1.list <- lapply(1:length(markers.id), function(f){
  FeaturePlot(s.data_RNA, features=markers.id[f], reduction="umap") + labs(title=markers.symbols[f])
})

patchwork::wrap_plots(f1.list)
```


# Calculate NT typing for cells

```{r NT typing preparation}
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R")
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")

NT.type.markers <- gene_set_prepare2("../metadata/onlyNT_markers311022.xlsx", "Brain")

#Renaming genes as gene names instead of ENSMUSG IDs
s.data_RNA<-RenameGenesSeurat(s.data_RNA,s.data_RNA[["RNA"]]@meta.features[,1])
DefaultAssay(s.data_RNA) <- 'RNA_name'

mouse.cc.genes <- read_xlsx("../metadata/Mouse_S_and_G2m_genes_KA.xlsx", sheet = "Sheet2")
mouse.g2m.genes <- dplyr::filter(mouse.cc.genes, !is.na(`Progenitor marker`) & phase=="G2m") %>% pull(gene_name)
mouse.s.genes <- dplyr::filter(mouse.cc.genes, !is.na(`Progenitor marker`) & phase=="S") %>% pull(gene_name)

#Creating scores for artificial genes: s & g2m 
s.data_RNA <- CellCycleScoring(
  object = s.data_RNA,
  g2m.features = str_to_title(mouse.g2m.genes),
  s.features = str_to_title(mouse.s.genes),
  search=TRUE
)

#Getting the expression data from the seurat object
exp.matr <- as.matrix(s.data_RNA[["RNA_name"]]@data)
#Adding the two 'genes' in the end of the matrix
matr <- rbind(exp.matr, s.data_RNA@meta.data$S.Score)
rownames(matr)[nrow(matr)] <- "S"
matr <- rbind(matr, s.data_RNA@meta.data$G2M.Score)
rownames(matr)[nrow(matr)] <- "G2m"
# scale the data 
matr <- t(scale(t(matr)))
```

```{r Calculating NT type estimation per cell}
# Getting cell-type by cell matrix.
es.max <- sctype_score(scRNAseqData = matr, scaled = TRUE, gs = NT.type.markers$gs_positive, gs2 = NT.type.markers$gs_negative)

cell.nt.types <- apply(es.max,2,function(score){
  tmp.thr <- mean(score) + (1.3*sd(score))
  if (max(score) > tmp.thr & max(score)>0){
    cell.nt.type <- names(which.max(score))
  } else {
    cell.nt.type <- "unknown"
  }
  return(cell.nt.type)
})

s.data_RNA <- AddMetaData(object=s.data_RNA,metadata = apply(es.max,2,function(x){names(which.max(x))}), col.name = "NT.type.max")
s.data_RNA <- AddMetaData(object=s.data_RNA,metadata = cell.nt.types, col.name = "NT.type")
```

```{r Add brain region information to metadata}
s.data_RNA <- AddMetaData(object = s.data_RNA, metadata = str_extract(colnames(s.data_RNA), pattern = "[a-z]{2}_\\d{1}|[r1]{2}_\\d{1}"), col.name = "brain_region.replicate")
s.data_RNA <- AddMetaData(object = s.data_RNA, metadata = str_extract(colnames(s.data_RNA), pattern = "[a-z]{2}|[r1]{2}"), col.name = "brain_region")
```

```{r Draw DimPlot with NT-types, fig.height=10, fig.width=10}
pdf(height = 8, width = 8, file=paste("/Users/kilpinen/OneDrive - University of Helsinki/Neuronal Feature Space/Figures/plots for figures/scRNA_NT_type_UMAP.",run.date,".pdf",sep=""))
pushViewport(viewport(gp = gpar(fontfamily = "Helvetica")))
palette <- ggsci::pal_igv()(length(unique(s.data_RNA$NT.type)))
DimPlot(s.data_RNA, reduction = "umap", label = FALSE, cols = palette, group.by = "NT.type", shuffle = TRUE) + coord_fixed() + ggtitle("")
dev.off()
```

```{r Draw DimPlot with cluster numbers, fig.height=10, fig.width=10}
pdf(height = 8, width = 8, file=paste("/Users/kilpinen/OneDrive - University of Helsinki/Neuronal Feature Space/Figures/plots for figures/scRNA_UMAP.",run.date,".pdf",sep=""))
pushViewport(viewport(gp = gpar(fontfamily = "Helvetica")))
palette <- distinctColorPalette(length(levels(Idents(s.data_RNA))))
DimPlot(s.data_RNA, reduction = "umap", label = TRUE, cols = palette) + coord_fixed() + ggtitle("") + NoLegend()
dev.off()
```

```{r Draw DimPlot with brain region, fig.height=10, fig.width=10}
pdf(height = 8, width = 8, file=paste("/Users/kilpinen/OneDrive - University of Helsinki/Neuronal Feature Space/Figures/plots for figures/scRNA_UMAP_brain_region.",run.date,".pdf",sep=""))
pushViewport(viewport(gp = gpar(fontfamily = "Helvetica")))
palette <- ggsci::pal_igv()(length(unique(s.data_RNA$brain_region)))
DimPlot(s.data_RNA, reduction = "umap", label = FALSE, cols = palette, group.by = "brain_region") + coord_fixed() + ggtitle("")
dev.off()
```

```{r Draw QC DimPlot with replicates separated}
replicates <- str_extract(colnames(s.data_RNA), pattern = "^.*replt?[:digit:]+")
s.data_RNA <- AddMetaData(s.data_RNA, metadata = replicates, col.name = "replicates")

pdf(height = 8, width = 8, file=paste("/Users/kilpinen/OneDrive - University of Helsinki/Neuronal Feature Space/Figures/plots for figures/scRNA_UMAP_replicates.",run.date,".pdf",sep=""))
pushViewport(viewport(gp = gpar(fontfamily = "Helvetica")))
palette <- ggsci::pal_igv()(length(unique(s.data_RNA$replicates)))
DimPlot(s.data_RNA, reduction = "umap", label = FALSE, cols = palette, group.by = "replicates", shuffle = TRUE) + coord_fixed() + ggtitle("")
dev.off()
```

```{r Draw QC DimPlot with embryo info}
embryo <- rep("",ncol(s.data_RNA))
embryo[replicates %in% c("di.repl1","mb.repl1","r1.repl1")] <- "embryo1"
embryo[replicates %in% c("di.repl2","mb.repl2","r1.repl2")] <- "embryo2"
s.data_RNA <- AddMetaData(s.data_RNA, metadata = embryo, col.name = "embryo")

pdf(height = 8, width = 8, file=paste("/Users/kilpinen/OneDrive - University of Helsinki/Neuronal Feature Space/Figures/plots for figures/scRNA_UMAP_embryo.",run.date,".pdf",sep=""))
pushViewport(viewport(gp = gpar(fontfamily = "Helvetica")))
palette <- ggsci::pal_igv()(length(unique(s.data_RNA$embryo)))
DimPlot(s.data_RNA, reduction = "umap", label = FALSE, cols = palette, group.by = "embryo") + coord_fixed() + ggtitle("")
dev.off()
```


```{r Find all markers}
all.markers <- tibble(FindAllMarkers(s.data_RNA, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25))
```

```{r Filter top 2 markers}
top2.markers <-all.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)
#top2.markers$feature_symbol <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = pull(top2.markers, gene), feature.format = "ens")
create_dt(top2.markers)
```

---

Table of top 2 markers per cluster

```{r Find all markers with stricter parameters}
top20.markers <- all.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
#top20.markers$feature_symbol <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = pull(top20.markers, gene), feature.format = "ens")
create_dt(top20.markers)
```

---

Table of top 20 markers per cluster

```{r Saving Seurat object for further use}
qsave(s.data_RNA, file = paste("../scRNA_data/E14_scRNAseq.",run.date,".qs", sep=""), nthreads = 6)
```

```{r sessionInfo}
sessionInfo()
```
