---
title: "R Notebook of E14vMB scATAC processing at clade level with pre-defined joint feature space"
output: html_notebook
---

```{r Libraries, include=FALSE}
load.libs <- c(
  "Signac",
  "tidyverse",
  "dplyr",
  "BSgenome.Mmusculus.UCSC.mm10",
  "RColorBrewer",
  "future",
  "GenomicRanges",
  "EnsDb.Mmusculus.v79",
  "dendextend",
  "Seurat")
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load(load.libs, update = FALSE, character.only = TRUE, install=FALSE)
status <- sapply(load.libs,require,character.only = TRUE)
if(all(status)){
    print("SUCCESS: You have successfully installed and loaded all required libraries.")
} else{
    cat("ERROR: One or more libraries failed to install correctly. Check the following list for FALSE cases and try again...\n\n")
    status
}

source("../../generic code/AuxFunctions.R")
```

```{r Setting multicore/multisession}
options(parallelly.makeNodePSOCK.setup_strategy = "sequential", future.globals.maxSize = 12 * 1024 ^ 3, future.seed=TRUE)
plan("multisession", workers = 6)
```

```{r Setting sample variables}
sample.name <- "E14VMB"
run.date <- "220622"
```

```{r Path to raw data}
raw.path <- "/Volumes/MyBookDuo/Data/e14vmb1_data/scATAC/"
```

```{r Reading predefined feature space}
clade.peaks <- readRDS("../../NeuronalFeatureSpace/analysis/joint.clade.peaks.180622.Rds")
```

# --- Data preprocessing and QC 
```{r Read cell-level information and fragments files}
# E14_DI_1_ATAC_v1-2 => E14_DI_1_0
repl0.0.singlecell <- read_csv(file = paste(raw.path,sample.name,"_0/outs/singlecell.csv", sep=""))
# E14_FB_1 => E14_DI_1_1
repl1.1.singlecell <- read_csv(file = paste(raw.path,sample.name,"_1/outs/singlecell.csv", sep=""))
# E14_FB_2 => E14_DI_1_2
repl2.2.singlecell <- read_csv(file = paste(raw.path,sample.name,"_2/outs/singlecell.csv", sep=""))

repl0.cells <- dplyr::filter(repl0.0.singlecell, is__cell_barcode == 1) %>% pull(barcode)
repl1.cells <- dplyr::filter(repl1.1.singlecell, is__cell_barcode == 1) %>% pull(barcode)
repl2.cells <- dplyr::filter(repl2.2.singlecell, is__cell_barcode == 1) %>% pull(barcode)

if (!file.exists( paste(raw.path,sample.name,"_0/outs/fragments.filtered.tsv.gz", sep=""))){
FilterCells(
  fragments = paste(raw.path,sample.name,"_0/outs/fragments.tsv.gz", sep=""),
  cells = repl0.cells,
  outfile = paste(raw.path,sample.name,"_0/outs/fragments.filtered.tsv.gz", sep=""),
  buffer_length = 256L,
  verbose = TRUE
)
}

if (!file.exists( paste(raw.path,sample.name,"_1/outs/fragments.filtered.tsv.gz", sep=""))){
FilterCells(
  fragments = paste(raw.path,sample.name,"_1/outs/fragments.tsv.gz", sep=""),
  cells = repl1.cells,
  outfile = paste(raw.path,sample.name,"_1/outs/fragments.filtered.tsv.gz", sep=""),
  buffer_length = 256L,
  verbose = TRUE
)
}

if (!file.exists( paste(raw.path,sample.name,"_2/outs/fragments.filtered.tsv.gz", sep=""))){
FilterCells(
  fragments = paste(raw.path,sample.name,"_2/outs/fragments.tsv.gz", sep=""),
  cells = repl2.cells,
  outfile = paste(raw.path,sample.name,"_2/outs/fragments.filtered.tsv.gz", sep=""),
  buffer_length = 256L,
  verbose = TRUE
)
}

repl0.fragments <- CreateFragmentObject(path = paste(raw.path,sample.name,"_0/outs/fragments.filtered.tsv.gz", sep=""), cells = repl0.cells, validate.fragments = FALSE)
repl1.fragments <- CreateFragmentObject(path = paste(raw.path,sample.name,"_1/outs/fragments.filtered.tsv.gz", sep=""), cells = repl1.cells, validate.fragments = FALSE)
repl2.fragments <- CreateFragmentObject(path = paste(raw.path,sample.name,"_2/outs/fragments.filtered.tsv.gz", sep=""), cells = repl2.cells, validate.fragments = FALSE)
```

```{r Defining used chromosomes}
used.chromosomes <- c("chr1", "chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19")
genome.lengths <- seqlengths(BSgenome.Mmusculus.UCSC.mm10)[names(seqlengths(BSgenome.Mmusculus.UCSC.mm10)) %in% used.chromosomes]
```

```{r Combine new Feature bin x cells matrix based on peaks detected from clades}

# Note dropping some chromosomes
clade.peak.feature.matrix.0 <- FeatureMatrix(
  fragments = repl0.fragments,
  features = keepSeqlevels(clade.peaks, used.chromosomes, pruning.mode = "coarse"),
  process_n = 5000,
  sep = c("-", "-"),
  verbose = TRUE
)

clade.peak.feature.matrix.1 <- FeatureMatrix(
  fragments = repl1.fragments,
  features = keepSeqlevels(clade.peaks, used.chromosomes, pruning.mode = "coarse"),
  process_n = 5000,
  sep = c("-", "-"),
  verbose = TRUE
)

clade.peak.feature.matrix.2 <- FeatureMatrix(
  fragments = repl2.fragments,
  features = keepSeqlevels(clade.peaks, used.chromosomes, pruning.mode = "coarse"),
  process_n = 5000,
  sep = c("-", "-"),
  verbose = TRUE
  )
```

```{r Create Chromatin assay}
chr.clade.peak.assay.0 <- CreateChromatinAssay(counts = clade.peak.feature.matrix.0, fragments = list(repl0.fragments), genome = seqinfo(BSgenome.Mmusculus.UCSC.mm10), ranges = StringToGRanges(rownames(clade.peak.feature.matrix.0)))

chr.clade.peak.assay.1 <- CreateChromatinAssay(counts = clade.peak.feature.matrix.1, fragments = list(repl1.fragments), genome = seqinfo(BSgenome.Mmusculus.UCSC.mm10), ranges = StringToGRanges(rownames(clade.peak.feature.matrix.1)))

chr.clade.peak.assay.2 <- CreateChromatinAssay(counts = clade.peak.feature.matrix.2, fragments = list(repl2.fragments), genome = seqinfo(BSgenome.Mmusculus.UCSC.mm10), ranges = StringToGRanges(rownames(clade.peak.feature.matrix.2)))
```

```{r Create Seurat objects from peak Chromatin assays}
repl0.metadata <- as.data.frame(dplyr::filter(repl0.0.singlecell, is__cell_barcode == 1))
rownames(repl0.metadata) <- repl0.metadata$barcode

repl1.metadata <- as.data.frame(dplyr::filter(repl1.1.singlecell, is__cell_barcode == 1))
rownames(repl1.metadata) <- repl1.metadata$barcode

repl2.metadata <- as.data.frame(dplyr::filter(repl2.2.singlecell, is__cell_barcode == 1))
rownames(repl2.metadata) <- repl2.metadata$barcode

repl0.s.data.peaks <- CreateSeuratObject(
  counts = chr.clade.peak.assay.0,
  assay = 'peaks_count',
  project = 'ATAC',
  meta.data = repl0.metadata
)

repl1.s.data.peaks <- CreateSeuratObject(
  counts = chr.clade.peak.assay.1,
  assay = 'peaks_count',
  project = 'ATAC',
  meta.data = repl1.metadata
)

repl2.s.data.peaks <- CreateSeuratObject(
  counts = chr.clade.peak.assay.2,
  assay = 'peaks_count',
  project = 'ATAC',
  meta.data = repl2.metadata
)
```

```{r Merge Seurat objects}
repl0.s.data.peaks$replicate <- '_0'
repl1.s.data.peaks$replicate <- '_1'
repl2.s.data.peaks$replicate <- '_2'
system.time(s.data <- merge(x = repl0.s.data.peaks, y = list(repl1.s.data.peaks,repl2.s.data.peaks), add.cell.ids = c("_0", "_1","_2")))
```

```{r Add gene annotations from Ensembl, include=FALSE}
# extract gene annotations from EnsDb
#annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79, standard.chromosomes = TRUE)

annotations <- readRDS("../../Github/AnalysisEnvironment/mm10/Ensembel_Mmusculus79_annotation.Rds")

# change to UCSC style since the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "mm10"

#ucsc.levels <- str_replace(string=paste("chr",seqlevels(annotations),sep=""), pattern="chrMT", replacement="chrM")
#seqlevels(annotations) <- ucsc.levels

# add the gene information to the object
Annotation(s.data) <- annotations
```

```{r Calculate nucleosome signal}
s.data <- NucleosomeSignal(object = s.data)
```

```{r Plotting }
s.data$nucleosome_group <- ifelse(s.data$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
FragmentHistogram(object = s.data, group.by = 'nucleosome_group', region = 'chr1-1-10000000')
```

```{r TSS enrichment}
s.data <- TSSEnrichment(s.data, fast = FALSE)
```

```{r Plot biological QC data, fig.width=14}
s.data$pct_reads_in_peaks <- s.data$peak_region_fragments / s.data$passed_filters * 100
s.data$blacklist_ratio <- s.data$blacklist_region_fragments / s.data$peak_region_fragments

VlnPlot(
  object = s.data,
  features = c('pct_reads_in_peaks', 'peak_region_fragments',
               'TSS.enrichment', 'blacklist_ratio', 'nucleosome_signal'),
  pt.size = 0.1,
  ncol = 5
)

# Storing merged clade level object as it takes so long to form
saveRDS(s.data,paste(sample.name,".merged.clade.phase.",run.date,".Rds",sep=""))
```

```{r Filter based on biological QC values}
s.data.filt <- subset(
  x = s.data,
  subset = peak_region_fragments > 3000 &
    peak_region_fragments < 25000 &
    pct_reads_in_peaks > 55 &
    blacklist_ratio < 0.015 &
    nucleosome_signal < 3 &
    TSS.enrichment > 4
)
s.data.filt
```

```{r Filtering based on number of cells per feature or vice versa in peak phase}
DefaultAssay(s.data.filt) <- 'peaks_count'
min.cells.thr <- round(length(unique(Cells(s.data.filt)))*0.01, digits = 0)
max.cells.thr <- round(length(unique(Cells(s.data.filt)))*0.975, digits = 0)

min.features.thr <- round(nrow(s.data.filt)*0.025, digits = 0)
max.features.thr <- round(nrow(s.data.filt)*0.975, digits = 0)

cell.per.feature <- rowSums(GetAssayData(s.data.filt[["peaks_count"]])>0)
feature.per.cell <- colSums(GetAssayData(s.data.filt[["peaks_count"]])>0)

feature.filter.index <- which(cell.per.feature >= min.cells.thr & cell.per.feature <= max.cells.thr)
cell.filter.index <- which(feature.per.cell >= min.features.thr & feature.per.cell <= max.features.thr)

features.to.keep <- rownames(s.data.filt)[feature.filter.index]
cells.to.keep <- Cells(s.data.filt)[cell.filter.index]

s.data.filt <- subset(s.data.filt, cells = cells.to.keep, features = features.to.keep)
s.data.filt
```

```{r Binarize counts for peak assay}
s.data.filt[["peaks"]] <- s.data.filt[["peaks_count"]]
DefaultAssay(s.data.filt) <- 'peaks'
s.data.filt <- BinarizeCounts(s.data.filt, assay = "peaks")
```

```{r Re-add genomic annotation to the Seurat object}
Annotation(s.data.filt) <- annotations
```

```{r Save data for downstream analysis}
saveRDS(s.data.filt, paste("../scATAC_data/",sample.name,".merged.peaks.",run.date,".Rds",sep=""))
``` 

```{r Env info}
# Conda env r411_291021
sessionInfo()
```