---
title: "E14vMB scRNA analysis with process and parameters standardized with rV2 project"
output: html_notebook
---

```{r Loading libraries, include=FALSE}
library(Seurat);
library(tidyverse);
library(ggplot2);
library(future);
library(org.Mm.eg.db);
library(randomcoloR);
library(DT);
library(data.table);
source("../../generic code/AuxFunctions.R");
```

```{r Setting Seurat multicore}
plan("multisession", workers = 6)
options(future.globals.maxSize = 12 * 1024 ^ 3, future.rng.onMisuse="ignore")
```

```{r Setting variable}
sample.name <- "E14VMB"
run.date <- "031121"
```

```{r Reading datafiles and form Seurat objects}
  repl1 <- Read10X(data.dir = "/Volumes/ExtSSD/ExtraWorkspace/e14vmb1_data/scRNA/E14VMB_1_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  s.repl1 <- CreateSeuratObject(counts = repl1, project = "repl1")

  repl2 <- Read10X(data.dir = "/Volumes/ExtSSD/ExtraWorkspace/e14vmb1_data/scRNA/E14VMB_2_RNA/outs/filtered_feature_bc_matrix/", gene.column = 1)
  s.repl2 <- CreateSeuratObject(counts = repl2, project = "repl2")
```

```{r Read Ensembl to gene name mapping from 10x datafiles for both Seurat objects}
feature.data.repl1 <- as.data.frame(setNames(fread("/Volumes/ExtSSD/ExtraWorkspace/e14vmb1_data/scRNA/E14VMB_1_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))

feature.data.repl2 <- as.data.frame(setNames(fread("/Volumes/ExtSSD/ExtraWorkspace/e14vmb1_data/scRNA/E14VMB_2_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz", header=FALSE), c("ensg_id","gene_name","exp_type")))
```


```{r Merging Seurat object}
s.data_RNA<- merge(x = s.repl1, y = s.repl2, add.cell.ids = c( "repl1", "repl2"), project = "s.data")
```

```{r Adding feature metadata after merge}
# Note, assumes identical feature metadata between replicates
s.data_RNA[['RNA']] <- AddMetaData(object = s.data_RNA[['RNA']], metadata = feature.data.repl1[,2], col.name="feature_symbol")
```

```{r Remove TDTOMATOG}
s.data_RNA <- subset(s.data_RNA, features=rownames(s.data_RNA)[!rownames(s.data_RNA)=="TDTOMATOG"])
```

```{r Calculate percentage of mt- features}
feature.map <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = rownames(s.data_RNA), feature.format = "ens")

mt.features <- rownames(s.data_RNA[grep("^MT-", feature.map, ignore.case = T)])

s.data_RNA[["percent.mt"]] <- PercentageFeatureSet(s.data_RNA, features = mt.features)
```

```{r Plot nFeature_RNA and mitochondrial genes per cell before filtering}
VlnPlot(s.data_RNA, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r Filtering likely cell doublets and noise}
s.data_RNA <- subset(s.data_RNA, subset = nFeature_RNA > 2500 & nFeature_RNA < 5500 & percent.mt < 15)
```

```{r Plot nFeature_RNA and mitochondrial genes per cell after filtering}
VlnPlot(s.data_RNA, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r LogNormalize data}
s.data_RNA <- NormalizeData(s.data_RNA, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r Finding variable features}
s.data_RNA <- FindVariableFeatures(s.data_RNA, selection.method = "vst", nfeatures = 3000)
```

```{r Scaling data while regressing percent.mt}
s.data_RNA <- ScaleData(s.data_RNA, vars.to.regress = c("percent.mt","nFeature_RNA","nCount_RNA"))
```

```{r Identify 10 most highly variable genes}
top10 <- head(VariableFeatures(s.data_RNA), 10)
```

```{r Plot variable features with and without labels}
plot1 <- VariableFeaturePlot(s.data_RNA)
plot1
LabelPoints(plot = plot1, points = top10, repel = TRUE, labels=convert_feature_identity(object = s.data_RNA, assay = "RNA", features = top10, feature.format = "ens"))
```

```{r RunPCA, include=FALSE}
s.data_RNA <- RunPCA(s.data_RNA, features = VariableFeatures(object = s.data_RNA))
```

```{r Plot DimPlot and DimHeatmap, fig.height=18, fig.width=18}
#DimHeatmap(s.data_RNA, dims = 1:20, cells = 500, balanced = TRUE)
```

```{r Calculate JackStraw data}
s.data_RNA <- JackStraw(s.data_RNA, num.replicate = 100, dims = 30)
s.data_RNA <- ScoreJackStraw(s.data_RNA, dims = 1:30)
```

```{r Plot Jackstraw plot}
JackStrawPlot(s.data_RNA, dims = 1:30)
```

```{r Draw Elbowplot}
ElbowPlot(s.data_RNA, ndims=30)
```

```{r Find neighbours and clusters}
s.data_RNA <- FindNeighbors(s.data_RNA, dims = 1:20)
s.data_RNA <- FindClusters(s.data_RNA, resolution = 2)
```

```{r RunUMAP}
  s.data_RNA <- RunUMAP(s.data_RNA, dims = 1:20, spread=1.5)
```

```{r Draw DimPlot}
palette <- distinctColorPalette(length(levels(Idents(s.data_RNA))))
DimPlot(s.data_RNA, reduction = "umap", label = TRUE, cols = palette)
```

```{r Some validation plots, fig.height=24, fig.width=18}
markers.symbols <-  c("Gad1", "Slc17a6", "Dlx1", "Tal2", "Pou4f1", "Dlx2","Ascl1","Nkx2-2", "Sst")
markers.id <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = markers.symbols, feature.format = "symbol")

f1.list <- lapply(1:length(markers.id), function(f){
  FeaturePlot(s.data_RNA, features=markers.id[f], reduction="umap") + labs(title=markers.symbols[f])
})

patchwork::wrap_plots(f1.list)
```

```{r Find all markers}
all.markers <- tibble(FindAllMarkers(s.data_RNA, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25))
```

```{r Filter top 2 markers}
top2.markers <-all.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)
top2.markers$feature_symbol <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = pull(top2.markers, gene), feature.format = "ens")
create_dt(top2.markers)
```

---

Table of top 2 markers per cluster

```{r Find all markers with stricter parameters}
top20.markers <- all.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
top20.markers$feature_symbol <- convert_feature_identity(object = s.data_RNA, assay = "RNA", features = pull(top20.markers, gene), feature.format = "ens")
create_dt(top20.markers)
```

---

Table of top 20 markers per cluster

```{r Saving Seurat object for further use}
saveRDS(s.data_RNA, file = paste("../scRNA/",sample.name,"scRNAseq.",run.date,".Rds", sep=""))
```


```{r}
# Conda env r411_291021
sessionInfo()
```

<!-- # Running again with non-neuronal cells excluded -->

<!-- ```{r Dropping non-brain cells} -->
<!--   # Based on earlier analysis of marker genes in clusters -->
<!--   non.neuronal.cells <- readRDS("../scRNA/non_neuronal_cells.Rds") -->

<!--   # Making barcodes to match this process pipeline, replicate label is different and -1 is missing from the end -->
<!--     non.neuronal.cells <- str_replace(non.neuronal.cells, pattern = "^DI1", replacement = "repl1") %>% str_replace(pattern = "^DI2", replacement = "repl2") -->
<!--     #non.neuronal.cells <- paste(non.neuronal.cells,"-1",sep="") -->

<!--     s.data.clean <- subset(s.data_RNA, cells = non.neuronal.cells) -->
<!-- ``` -->

<!-- ```{r Rescale clean subset} -->
<!--   s.data.clean <- ScaleData(s.data.clean, vars.to.regress = "percent.mt") -->
<!-- ``` -->

<!-- ```{r Find variable features in clean subset} -->
<!--   s.data.clean <- FindVariableFeatures(s.data.clean, selection.method = "vst", nfeatures = 3000) -->
<!-- ``` -->

<!-- ```{r Top10 most variable features} -->
<!--   top10 <- head(VariableFeatures(s.data.clean), 10) -->
<!-- ``` -->

<!-- ```{r Rescale} -->
<!--   # FIXME:Why again double scaling? -->
<!--   all.genes <- rownames(s.data.clean) -->
<!--   s.data.clean <- ScaleData(s.data.clean, features = all.genes) -->
<!-- ``` -->

<!-- ```{r RunPCA for cleaned data, include=FALSE} -->
<!--   s.data.clean <- RunPCA(s.data.clean, features = VariableFeatures(object = s.data.clean)) -->
<!--   #print(s.data.clean[["pca"]], dims = 1:20, nfeatures = 10) -->
<!-- ``` -->

<!-- ```{r Plot PCA} -->
<!--   # print(MB14_clean[["pca"]], dims = 1:20, nfeatures = 10) -->
<!--   DimPlot(s.data.clean, reduction = "pca") -->
<!-- ``` -->

<!-- ```{r Plot DimHeatmap, fig.height=18, fig.width=18} -->
<!--   DimHeatmap(s.data.clean, dims = 1:25, cells = 500, balanced = TRUE) -->
<!-- ``` -->

<!-- ```{r Calculate and plot JackStrawPlot} -->
<!--   s.data.clean <- JackStraw(s.data.clean, num.replicate = 100, dims = 28) -->
<!--   s.data.clean <- ScoreJackStraw(s.data.clean, dims = 1:28) -->
<!--   JackStrawPlot(s.data.clean, dims = 1:28) -->
<!-- ``` -->

<!-- ```{r Plot ElbowPlot} -->
<!--   ElbowPlot(s.data.clean, ndims = 28) -->
<!-- ``` -->

<!-- ```{r Find neighbours and perform clustering} -->
<!--   s.data.clean <- FindNeighbors(s.data.clean, dims = 1:28) -->
<!--   s.data.clean <- FindClusters(s.data.clean, resolution = 1.4, algorithm = 4) -->
<!-- ``` -->

<!-- ```{r Calculate and plot UMAP} -->
<!--   s.data.clean <- RunUMAP(s.data.clean, dims = 1:28) -->
<!--   palette.clean <- distinctColorPalette(length(levels(Idents(s.data.clean)))) -->
<!--   DimPlot(s.data.clean, reduction = "umap",label = TRUE, cols = palette.clean) -->
<!-- ``` -->

<!-- ```{r Plot Featureplots, fig.height=18, fig.width=18} -->
<!--   FeaturePlot(s.data.clean, reduction = "umap", features = c("Gad1", "Slc17a6", "Dlx1", "Tal2", "Pou4f1", "Dlx2","Ascl1","Nkx2-2", "Sst"), pt.size = 2) -->
<!-- ``` -->

<!-- ```{r Find markers and write out, include=FALSE} -->
<!--   s.data.clean.markers <- FindAllMarkers(s.data.clean, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25) -->
<!--   write.csv(x = s.data.clean.markers, file="MB14.cleaned.markers_all.csv") -->
<!--   s.data.clean.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC) %>% write.csv(file="E14_MB_scRNAseq_cleaned_top20_allclusters.csv") -->
<!-- ``` -->


<!-- ```{r Create interactive table for top20 markers} -->
<!-- top20 <- s.data.clean.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC) -->
<!-- create_dt(top20) -->
<!-- ``` -->

<!-- --- -->

<!-- Table of top20 markers per cluster -->

<!-- ```{r Saving final Seurat object for further use} -->
<!--   saveRDS(s.data.clean, file = "../scRNA/E14_s.data_scRNAseq.clean.rds") -->
<!-- ``` -->
