---
title: "R Notebook of exploring GABAergic fate among E14DI,E14MB cells E14R1 cells"
output: html_notebook
---


```{r}
library(Seurat)
library(Signac)
library(tidyverse)
library(BSgenome.Mmusculus.UCSC.mm10)
library(RColorBrewer)
library(future)
library(GenomicRanges)
library(EnsDb.Mmusculus.v79)
library(dendextend)
library(DT)
library(ChIPpeakAnno)
library(Repitools)
library(BiocManager)
library(ChIPseeker)
library(circlize)
library(ComplexHeatmap)
library(dendextend)
library(fpc)
library(ggsci)
library(qs)
source("../../generic code/AuxFunctions.R")
```

```{r Read cell types information}
cell.types <- readxl::read_xlsx("/Users/kilpinen/OneDrive - University of Helsinki/Neuronal Feature Space/Cell types master table 280622 joint feature space.xlsx", sheet="cell types labels")
```


```{r Read data from each E14 region}
s.data.e14r1 <- readRDS("../scATAC_data/E14vR1_DownstreamReady.230622.RNA.pos.idents.Rds")
s.data.mb <- readRDS("../scATAC_data/E14VMB_DownstreamReady.230622.RNA.pos.idents.Rds")
s.data.di <- readRDS("../scATAC_data/E14DI1_DownstreamReady.220622.RNA.pos.idents.Rds")
```

```{r Merge regions into same Seurat object - peaks}
s.data.e14r1$dataset <- 'r1'
s.data.mb$dataset <- 'mb'
s.data.di$dataset <- 'di'

DefaultAssay(s.data.di) <- "peaks"
DefaultAssay(s.data.mb) <- "peaks"
DefaultAssay(s.data.e14r1) <- "peaks"

# Pick only joint features among objects
joint.features <- intersect(intersect(rownames(s.data.mb),rownames(s.data.di)),rownames(s.data.e14r1))

s.data.e14.all <- merge(subset(s.data.di,features=joint.features), c(subset(s.data.mb, features=joint.features),subset(s.data.e14r1, features=joint.features)), add.cell.ids=c("di","mb","r1"), merge.data=TRUE)

Idents(s.data.e14) <- paste(s.data.e14$dataset, Idents(s.data.e14),sep=".")

# Add NT type as metadata
nt.data <- dplyr::select(cell.types, `Cluster id`, Neurotransmitter)
colnames(nt.data)[1] <- "cluster"
nt.data[,"cluster"] <- pull(nt.data,cluster) %>% str_replace(pattern="^e14","")
nt.metadata <- left_join(tibble(cluster=Idents(s.data.e14)),nt.data)
s.data.e14 <- AddMetaData(s.data.e14, metadata = pull(nt.metadata,Neurotransmitter), col.name = "NT_type")
```

```{r Calculate UMAP of all E14 regions merged}
s.data.e14 <- RunTFIDF(s.data.e14)
s.data.e14 <- FindTopFeatures(s.data.e14, min.cutoff = 20)
s.data.e14 <- RunSVD(s.data.e14)
s.data.e14 <- RunUMAP(s.data.e14, dims = 2:50, reduction = 'lsi')
```

```{r UMAP with brain region}
DimPlot(s.data.e14, group.by = 'dataset', pt.size = 0.1) + ggtitle("Brain region")
```

```{r}
DimPlot(s.data.e14, group.by = 'NT_type', pt.size = 0.1) + ggtitle("Neurotransmitter type")
```

```{r Calculate dendrogram of all clusters}
e14.cluster.averages <- AverageExpression(s.data.e14, assays="peaks")
cell.dist.e14 <- proxy::dist(e14.cluster.averages$peaks, method="cosine", by_rows=FALSE)
hclust_cells_e14 <- hclust(cell.dist.e14, method="ward.D2")
hcd_e14 <- as.dendrogram(hclust_cells_e14)
hcd_e14 <- hcd_e14 %>% set("branches_lwd", 8)

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[1] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[1]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[2] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[2]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[3] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[3]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[4] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[4]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[5] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[5]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[6] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[6]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[7] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col",pal_jco()(8)[7]
  )

hcd_e14 <- hcd_e14 %>% branches_attr_by_labels(
    labels=dplyr::filter(nt.data, Neurotransmitter==unique(nt.data$Neurotransmitter)[8] & !grepl(nt.data$cluster, pattern="^e12")) %>% pull(cluster),
    type="all", attr="col", pal_jco()(8)[8]
  )
```


```{r Plot all cluster dendrogam with Circos, fig.width=14, fig.height=14}
#hcd.upper.circ  <- hcd.upper
par(mar = rep(4,4))
circos.initialize("leaf.labels", xlim = c(0, length(labels(hcd_e14))))

circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
   circos.text(1:length(labels(hcd_e14))-0.5, rep(0, length(labels(hcd_e14))), labels(hcd_e14), col = labels_colors(hcd_e14),
               facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5), cex=3)
}, bg.border = NA, track.height = 0.15)
max_height = attr(hcd_e14, "height")
# circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
#    circos.barplot(t(sample.clade.prop),1:ncol(sample.clade)-0.5, col=pal_jco()(4))
# }, track.height =.15, bg.border = NA)

circos.track(ylim = c(0, max_height), panel.fun = function(x, y) {
   circos.dendrogram(hcd_e14, max_height = max_height)
}, track.height =.60, bg.border = NA)

lgd_barplot = packLegend(
   Legend(at = unique(nt.data$Neurotransmitter), type = "lines",labels_gp = gpar(col = "black", cex = 2), legend_gp = gpar(col=pal_jco()(8), lwd = 8), title_position = "topleft", title_gp = gpar(cex = 2), title = "Neurotransmitter type", size = unit(4, "mm"))
     )
# 
draw(lgd_barplot, x = unit(2, "cm"), y = unit(2, "cm"), just = c("left", "bottom"))

circos.clear()
```

# GABA only

```{r}
# Take all GABA cells
GABA.clusters <- cell.types %>% dplyr::filter(Neurotransmitter=="GABAergic neurons" & `Brain region` %in% c("DI","MB","R1")) %>% pull(`Cluster id`) %>% str_replace(pattern="^e14","")
GABA.e14.data <- subset(s.data.e14, idents=GABA.clusters)
# Draw circos plot of their dendrogram, highlight all DA regions somehow
```

```{r GABA selector averages}
s.data.di<-RenameGenesSeurat(s.data.di,s.data.di[["RNA"]]@meta.features[,1])
DefaultAssay(s.data.di) <- "RNA_name"
di.avg <- AverageExpression(s.data.di)

s.data.mb<-RenameGenesSeurat(s.data.mb,s.data.mb[["RNA"]]@meta.features[,1])
DefaultAssay(s.data.mb) <- "RNA_name"
mb.avg <- AverageExpression(s.data.mb)

s.data.e14r1<-RenameGenesSeurat(s.data.e14r1,s.data.e14r1[["RNA"]]@meta.features[,1])
DefaultAssay(s.data.e14r1) <- "RNA_name"
r1.avg <- AverageExpression(s.data.e14r1)

GABA.fate.selectors <- c("Tal1","Dlx1","Dlx2")
```


```{r Recalculate GABA only scATAC UMAP}
GABA.e14.data <- RunTFIDF(GABA.e14.data)
GABA.e14.data <- FindTopFeatures(GABA.e14.data, min.cutoff = 20)
GABA.e14.data <- RunSVD(GABA.e14.data)
GABA.e14.data <- RunUMAP(GABA.e14.data, dims = 2:50, reduction = 'lsi')
DimPlot(GABA.e14.data, group.by = 'ident', pt.size = 0.5)
# TODO: Switch this to Cell type labels
```

```{r}
GABA.cluster.averages <- AverageExpression(GABA.e14.data, assays="peaks")
cell.dist.gaba <- proxy::dist(GABA.cluster.averages$peaks, method="cosine", by_rows=FALSE)
hclust_cells.gaba <- hclust(cell.dist.gaba, method="ward.D2")
hcd_gaba <- as.dendrogram(hclust_cells.gaba)
```

```{r}
cluster.order <- labels(hcd_gaba)
di.clusters <- cluster.order[grepl(cluster.order, pattern = "di.*")] %>% str_remove("di.") %>% as.numeric()
mb.clusters <- cluster.order[grepl(cluster.order, pattern = "mb.*")] %>% str_remove("mb.") %>% as.numeric()
r1.clusters <- cluster.order[grepl(cluster.order, pattern = "r1.*")] %>% str_remove("r1.") %>% as.numeric()

di.selector.exp <- di.avg$RNA_name[GABA.fate.selectors,di.clusters]
colnames(di.selector.exp) <- paste("di.",colnames(di.selector.exp),sep="")

mb.selector.exp <- mb.avg$RNA_name[GABA.fate.selectors,mb.clusters]
colnames(mb.selector.exp) <- paste("mb.",colnames(mb.selector.exp),sep="")

r1.selector.exp <- r1.avg$RNA_name[GABA.fate.selectors,r1.clusters]
colnames(r1.selector.exp) <- paste("r1.",colnames(r1.selector.exp),sep="")

combined.sel.exp <- cbind(di.selector.exp,mb.selector.exp,r1.selector.exp)[,cluster.order]

col_fun = colorRamp2(c(min(combined.sel.exp), 0, max(combined.sel.exp)), c("red", "white", "green"))
```


```{r Draw GABA only circos dendrogram, fig.height=6, fig.width=6}
circos.clear()
par(mar = rep(4,4))
circos.initialize("leaf.labels", xlim = c(0, length(labels(hcd_gaba))))

circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
   circos.text(1:length(labels(hcd_gaba))-0.5, rep(0, length(labels(hcd_gaba))), labels(hcd_gaba), col = labels_colors(hcd_gaba),
               facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5), cex=1)
}, bg.border = NA, track.height = 0.15)
max_height = attr(hcd_gaba, "height")

circos.heatmap(as.matrix(t(combined.sel.exp)), cluster=FALSE, col = col_fun,  dend.side="none")

circos.track(ylim = c(0, max_height), panel.fun = function(x, y) {
   circos.dendrogram(hcd_gaba, max_height = max_height)
}, track.height =.40, bg.border = NA)



circos.clear()

```

