---
title: "R Notebook of UMAP and feature plots for manuscript"
output: html_notebook
---

```{r Libraries}
library(tidyverse)
library(Seurat)
library(Signac)
source("../../generic code/AuxFunctions.R")
```

```{r Genes for featureplost}
marker.genes <- readxl::read_xlsx("../cell type markers_280722.xlsx") %>% dplyr::filter(`Gene type`=="neurotransmission")
```

# E14DI part

```{r Loading E14DI downstream object}
s.data.e14di <- readRDS("../scATAC_data/E14DI1_DownstreamReady.220622.RNA.pos.idents.Rds")
```

```{r E14DI scATAC UMAP, fig.height=16,fig.width=16}
DimPlot(object = s.data.e14di, label = TRUE, pt.size=1.2, label.size = 10) + NoLegend() + coord_equal()
```

```{r E14DI Featureplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e14di) <- 'RNA'

s.data.e14di<-RenameGenesSeurat(s.data.e14di,s.data.e14di[["RNA"]]@meta.features[,1])

DefaultAssay(s.data.e14di) <- 'RNA_name'

s.data.e14di <- CellCycleScoring(
  object = s.data.e14di,
  g2m.features = str_to_title(cc.genes$g2m.genes),
  s.features = str_to_title(cc.genes$s.genes),
  search=TRUE
)

DefaultAssay(s.data.e14di) <- 'RNA_name'

f.plot.tmp <- FeaturePlot(
  object = s.data.e14di,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  pt.size = 0.1,
  max.cutoff = 'q95',
  combine = F
)

f.plots.1 <- lapply(1:length(f.plot.tmp),function(i){
  f.plot.tmp[[i]]
})

patchwork::wrap_plots(f.plots.1)
```

```{r E14DI Dotplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e14di) <- 'RNA_name'

f.plot.tmp.dot <- DotPlot(
  object = s.data.e14di,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  cluster.idents = TRUE,
  cols=c("red","green")
)
f.plot.tmp.dot  + scale_x_discrete(guide = guide_axis(n.dodge = 2)) + theme(text=element_text(size=22), axis.text = element_text(size=16)) + ylab("Cluster number") + xlab("Marker genes")
```

# E14vMB part

```{r Loading E14vMB downstream object}
s.data.e14mb <- readRDS("../scATAC_data/E14VMB_DownstreamReady.230622.RNA.pos.idents.Rds")
```

```{r E14vMB scATAC UMAP, fig.height=16,fig.width=16}
DimPlot(object = s.data.e14mb, label = TRUE, pt.size=1.2, label.size = 10) + NoLegend() + coord_equal()
```

```{r E14vMB Featureplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e14mb) <- 'RNA'

s.data.e14mb<-RenameGenesSeurat(s.data.e14mb,s.data.e14mb[["RNA"]]@meta.features[,1])

DefaultAssay(s.data.e14mb) <- 'RNA_name'

s.data.e14mb <- CellCycleScoring(
  object = s.data.e14mb,
  g2m.features = str_to_title(cc.genes$g2m.genes),
  s.features = str_to_title(cc.genes$s.genes),
  search=TRUE
)

DefaultAssay(s.data.e14mb) <- 'RNA_name'

f.plot.tmp <- FeaturePlot(
  object = s.data.e14mb,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  pt.size = 0.1,
  max.cutoff = 'q95',
  combine = F
)

f.plots.1 <- lapply(1:length(f.plot.tmp),function(i){
  f.plot.tmp[[i]]
})

patchwork::wrap_plots(f.plots.1)
```

```{r E14vMB Dotplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e14mb) <- 'RNA_name'

f.plot.tmp.dot <- DotPlot(
  object = s.data.e14mb,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  cluster.idents = TRUE,
  cols=c("red","green")
)
f.plot.tmp.dot  + scale_x_discrete(guide = guide_axis(n.dodge = 2)) + theme(text=element_text(size=22), axis.text = element_text(size=16)) + ylab("Cluster number") + xlab("Marker genes")
```


# E14R1 part

```{r Loading E14R1 downstream object}
s.data.e14r1 <- readRDS("../scATAC_data/E14vR1_DownstreamReady.230622.RNA.pos.idents.Rds")
```

```{r E14R1 scATAC UMAP, fig.height=16,fig.width=16}
DimPlot(object = s.data.e14r1, label = TRUE, pt.size=1.2, label.size = 10) + NoLegend() + coord_equal()
```
```{r E14R1 Featureplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e14r1) <- 'RNA'

s.data.e14r1<-RenameGenesSeurat(s.data.e14r1,s.data.e14r1[["RNA"]]@meta.features[,1])

DefaultAssay(s.data.e14r1) <- 'RNA_name'

s.data.e14r1 <- CellCycleScoring(
  object = s.data.e14r1,
  g2m.features = str_to_title(cc.genes$g2m.genes),
  s.features = str_to_title(cc.genes$s.genes),
  search=TRUE
)

DefaultAssay(s.data.e14r1) <- 'RNA_name'

f.plot.tmp <- FeaturePlot(
  object = s.data.e14r1,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  pt.size = 0.1,
  max.cutoff = 'q95',
  combine = F
)

f.plots.1 <- lapply(1:length(f.plot.tmp),function(i){
  f.plot.tmp[[i]]
})

patchwork::wrap_plots(f.plots.1)
```

```{r E14R1 Dotplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e14r1) <- 'RNA_name'

f.plot.tmp.dot <- DotPlot(
  object = s.data.e14r1,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  cluster.idents = TRUE,
  cols=c("red","green")
)
f.plot.tmp.dot  + scale_x_discrete(guide = guide_axis(n.dodge = 2)) + theme(text=element_text(size=22), axis.text = element_text(size=16)) + ylab("Cluster number") + xlab("Marker genes")
```


# E12R1 part

```{r Loading E12R1 downstream object}
s.data.e12r1 <- readRDS("../scATAC_data/E12R1_DownstreamReady.230622.RNA.pos.idents.Rds")
```

```{r E12R1 scATAC UMAP, fig.height=16,fig.width=16}
DimPlot(object = s.data.e12r1, label = TRUE, pt.size=1.2, label.size = 10) + NoLegend() + coord_equal()
```

```{r E12R1 Featureplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e12r1) <- 'RNA'

s.data.e12r1<-RenameGenesSeurat(s.data.e12r1,s.data.e12r1[["RNA"]]@meta.features[,1])

DefaultAssay(s.data.e12r1) <- 'RNA_name'

s.data.e12r1 <- CellCycleScoring(
  object = s.data.e12r1,
  g2m.features = str_to_title(cc.genes$g2m.genes),
  s.features = str_to_title(cc.genes$s.genes),
  search=TRUE
)

DefaultAssay(s.data.e12r1) <- 'RNA_name'

f.plot.tmp <- FeaturePlot(
  object = s.data.e12r1,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  pt.size = 0.1,
  max.cutoff = 'q95',
  combine = F
)

f.plots.1 <- lapply(1:length(f.plot.tmp),function(i){
  f.plot.tmp[[i]]
})

patchwork::wrap_plots(f.plots.1)
```
```{r E12R1 Dotplots, fig.height=22, fig.width=26}
DefaultAssay(s.data.e12r1) <- 'RNA_name'

f.plot.tmp.dot <- DotPlot(
  object = s.data.e12r1,
  features = c(pull(marker.genes,GeneSymbol),"G2M.Score","S.Score"),
  cluster.idents = TRUE,
  cols=c("red","green")
)
f.plot.tmp.dot  + scale_x_discrete(guide = guide_axis(n.dodge = 2)) + theme(text=element_text(size=22), axis.text = element_text(size=16)) + ylab("Cluster number") + xlab("Marker genes")
```
